### ISSUE TITLE
Sound quality for 'First Steps With Data Frames' video makes it very difficult to endure

### ISSUE THREAD

**Issue by pjgoodall** [JuliaAcademy/DataFrames#10]
About  3000 people have started this video: [First Steps With Data Frames (2/6)](https://youtu.be/imsVOX68SfI)
The audience was 1,519 for the third video. I'm postulating half of the audience dropped out because of a combination of poor sound quality, and errors in the automatic set-up.

I have English as a first language, and I expect many of the audience have English as a second language. If I'm struggling to follow the audio track, then people with English second with find it very difficult. 

The DataFrames package is very nicely put together - thanks!

**Comment by bkamins** [comment]
> poor sound quality

This is an outdated video. Please check https://www.youtube.com/watch?v=OCCkbUL_x_c (and this one is linked in JuliaAcademy).
How did you find the previous video?

> and errors in the automatic set-up.

Could you please elaborate more on this? Does following the instructions in https://www.youtube.com/watch?v=aRR_xfQiqdc fail?

Thank you!

**Comment by pjgoodall** [comment]
I found the old tutorial by searching with Google for `julialang DataFrames tutorial'. The new tutorial is very good. Thank-you for your efforts!
