### ISSUE TITLE
Local Project.toml needs to be activated

### ISSUE THREAD

**Issue by vntmb** [JuliaAcademy/DataFrames#12]
Had an issue with `1. Environment setup.ipynb` where running `] instantiate` as explained in the notebook did not work. First I had to run:
```
using Pkg
Pkg.activate(".")
```
then the command worked

**Comment by bkamins** [comment]
As explained in https://julialang.github.io/IJulia.jl/stable/manual/usage/#Julia-projects you should not need to do this. Either you have a custom Jupyter kernel (in which case potentially you need to do something else than is normally needed) or you hit a bug in IJulia.jl. If it is the latter case can you please open an issue in IJulia.jl? (after double checking that indeed your IJulia does not automatically activate the local Project.toml).

Thank you for reporting!
