### ISSUE TITLE
Lesson 2: xlim / ylim

### ISSUE THREAD

**Issue by jzsfvss** [JuliaAcademy/DataFrames#13]
In the file "2. First steps with data frames.ipynb" the variables xlim and ylim cannot be assigned as currently shown without errors (running it in the shell). I get the following:

> ERROR : cannot assign a value to variable PyPlot.xlim from module Main

I suggest resolving this by replacing xlim / ylim with xlim0 / ylim0 everywhere in the notebook.

(Thank you for the amazing package!)

**Comment by bkamins** [comment]
I cannot reproduce the issue.

You must have manually used `xlim` and `ylim` from the PyPlot.jl before running example code from the notebook (which I do not do). Here is an example from the terminal:
```
julia> using PyPlot

julia> xlim = 10 # no problem with setting xlim to whatever you want
10

julia> methods(PyPlot.ylim) # error, as you have just introduced ylim from PyPlot in Main module
# 1 method for generic function "ylim":
[1] ylim(args...; kws...) in PyPlot at C:\Users\bogum\.julia\packages\PyPlot\XaELc\src\PyPlot.jl:173

julia> ylim = 10
ERROR: cannot assign a value to variable PyPlot.ylim from module Main
```

If you did this then indeed my `xlim` and `ylim` variables would require re-naming.

Having said that, for safety, I will rename these variables

**Comment by bkamins** [comment]
Thank you for reporting.
