### ISSUE TITLE
Activate step is needed

### ISSUE THREAD

**Issue by EvandroJRSilva** [JuliaAcademy/DataFrames#15]
I started the course and installed all needed packages (with more recent versions). However, I missed some details namely the environment activation.

As a newcomer to Julia language some things still go unoticed to me and the environment activation is a thing I learned few minutes ago when trying to fix a bug on the second notebook. As I tried to run the cell `using DataFrames` I was getting the error:

> ERROR: LoadError: ArgumentError: Package PrettyTables does not have LaTeXStrings in its dependencies ...

There are few helpful pages on this matter, specially to newcomers as I am. However one term caught my attention: environment. In one page someone refers to a global environment (@1.8.0 in my case).

I then tried all cited solutions as `instantiate`, `resolve`, `update`, etc. Nothing was fixing the related error. I went to Project.toml and Manifest.toml (of my @1.8.0), everything seemed right with no error and with the dependencies declared. I could not understand what was causing the error.

I finally came to this issue tab and opened #1. The issue was similar to mine and reading the answers things started to became clear. Then I read #2 and #12 and my mind opened to the real solution: I had to set the environment. After a fast search on google I found how to change the global environment to the one that came together with this repo. After activation was done the `status` asked to download missing packages with `instantiate`. All things done and ok, the error is gone.

I made this entire 'report' for two reasons. First, to help other newcomers as I am, who will face this same problem; second, to ask for an update in the first notebook to make it clear what environment setup stands for and a link to the respective documentation (for those who missed this part as I did). A cell with `pkg> activate .` command might help.

One final and important information: I'm using VS Code, and my Jupyter extension did not automatically activate the correct environment. That's another reason for this entire experience I had.

**Comment by bkamins** [comment]
>  I'm using VS Code, and my Jupyter extension did not automatically activate the correct environment.

So this is the core of the problem I think. It seems that VS Code does not fully correctly handle Jupyter Notebooks.
If you used standard Jupyter Notebook in web browser all would work.

But my question to you is: what exactly would you recommend to write and where (I mean - what exact sentence would be clear for you so that I can add it). Thank you!

**Comment by EvandroJRSilva** [comment]
Thanks for your response.

My suggestion is to add a bit information after 

> Jupyter Notebook automatically activates project environment if it is found in the working directory.

Something like: 

"Depending on the editor, e.g. VS Code, Jupyter Notebook may not automatically activate the environment. To be sure, start Julia within this project folder then press ']' and type `activate .`. If the correct environment is not activated you might face some unexpected issues with the packages. To see more details about Julia environments click here [https://pkgdocs.julialang.org/v1/environments]"

**Comment by bkamins** [comment]
OK - I pushed appropriate changes to all notebooks. Thank you!
