### ISSUE TITLE
Update to DataFrames.jl 1.1.1

### ISSUE THREAD

**Issue by bkamins** [JuliaAcademy/DataFrames#6]
@logankilpatrick - I have updated the tutorial to DataFrames.jl 1.1.1. As I was planning this move earlier the videos no not require updating (I made the codes in a way that still works the same way as in 0.22 version).

However, could you please update https://juliaacademy.com/ and https://juliaacademy.com/p/introduction-to-dataframes-jl1 page to indicate that the material is both for DataFrames.jl 0.22 and 1.1 (stressing visually 1.1, as 0.22 is not maintained any more and should not be used).

Thank you!

**Comment by logankilpatrick** [comment]
Done!

**Comment by bkamins** [comment]
Thank you!
