### ISSUE TITLE
Error in descriptive text in part 3 of Introduction to DataFrames.jl

### ISSUE THREAD

**Issue by semmottos** [JuliaAcademy/DataFrames#8]
The error (2 in fact) is missing of a colon in front of 'name' in the last two examples of this passage which should read like this:

It can be achieved like this:

df1_2[:, :name] = df_raw.name
or like this

df1_2.name = df_raw[:, :name]
We could also write:

df1_2[:, :name] = df_raw[:, :name]

**Comment by bkamins** [comment]
Fixed. Thank you!

**Comment by semmottos** [comment]
Thank YOU for your work on DataFrames!
